language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의  Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r plafoo-front *
  - mkdir -p deploy
  - mv plafoo-front.zip deploy/plafoo-front.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis  repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: pf-f-deploy-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: jhleon86/pf-f #Github  주소
      branch: master
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: pf-f-deploy-s3 # S3 버킷
    key: plafoo-front.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: plafoo-front # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: plafoo-front-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-southeast-1
    wait-until-deployed: true
    on:
      repo: jhleon86/pf-f
      branch: master      
  
      
# CI 실행 완료시 메 일로 알람
notifications:
  email:
    recipients:
      - jhleon869@gmail.com